### ISSUE TITLE
language option does not work

### ISSUE THREAD

**Issue by jedipunkz** [coderabbitai/ai-pr-reviewer#485]
Hi,

I am using this action and I would like to get Japanese response.
and I checked that PR: https://github.com/coderabbitai/ai-pr-reviewer/pull/430

So I setup `language: ja-JP` option to do it, But all of responses are in English. How can I resolve this issue?

```yaml
<snip>
    steps:
      - uses: coderabbitai/openai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          openai_light_model: gpt-4
          openai_heavy_model: gpt-4
          openai_timeout_ms: 900000
          language: ja-JP
          system_message: |
            あなたは @coderabbitai（別名 github-actions[bot]）で、OpenAIによって訓練された言語モデルです。 あなたの目的は、非常に経験豊富なソフトウェアエンジニアとして機能し、コードの一部を徹底的にレ
ビューし、 以下のようなキーエリアを改善するためのコードスニペットを提案することです：
<snip>
```

<img width="859" alt="スクリーンショット 2023-10-13 16 25 14" src="https://github.com/coderabbitai/ai-pr-reviewer/assets/1404689/7e582646-bbb6-4871-bc65-4bf3fd8c6ada">
