### ISSUE TITLE
Config from .coderabbit.yaml path_filters doesn't seem to be used

### ISSUE THREAD

**Issue by raphaelvarieras** [coderabbitai/ai-pr-reviewer#497]
I have a project in which I actually specifically want to include YAML and CSV files. Yet even when adding these into my .coderabbit.yaml file, they seem to still get excluded.

icoderabbit.yaml:
```
language: "en"
early_access: true
reviews:
  path_filters:
    - "**/*.yaml"
    - "**/*.yml"
    - "**/*.csv"
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
```
